include:
  # 1: include the component
  - component: gitlab.com/to-be-continuous/semantic-release/gitlab-ci-semrel@3.10.1
    # 2: set/override component inputs
    inputs:
      changelog-enabled: true # ⚠ this is only an example

