version: "3.5"

services:
  portfolio-database:
    image: postgres:15.1
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - database_network
    env_file: .env
    ports:
      - "5432:5432"

  portfolio-redis:
    image: redis:7.0.8
    networks:
      - redis_network

  portfolio-django:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DJANGO_SECRET_KEY
    depends_on:
      - portfolio-database
      - portfolio-redis
    command: gunicorn portfolio.wsgi -c gunicorn.cfg.py --reload --access-logfile -
    volumes:
      - ./_app:/usr/src/app
    networks:
      - database_network
      - redis_network
    ports:
      - "8000:8000"
    env_file: .env

volumes:
  database_volume:

networks:
  database_network:
  redis_network:
