# Generated by Django 5.1.4 on 2024-12-07 22:19

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="description_fr",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="details_en",
            field=models.ManyToManyField(null=True, to="portfolio.servicedetail"),
        ),
        migrations.AddField(
            model_name="service",
            name="details_fr",
            field=models.ManyToManyField(null=True, to="portfolio.servicedetail"),
        ),
        migrations.AddField(
            model_name="service",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="portfolio-media"
                ),
                upload_to="blog/",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="image",
            field=models.ImageField(
                null=True,
                storage=django_minio_backend.models.MinioBackend(
                    bucket_name="portfolio-media"
                ),
                upload_to="services/",
            ),
        ),
    ]
