# Generated by Django 4.2.3 on 2023-10-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_service_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='position',
            new_name='contract_type',
        ),
    ]
