# Generated by Django 5.1.4 on 2024-12-07 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_service_description_en_service_description_fr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="details_en",
        ),
        migrations.RemoveField(
            model_name="service",
            name="details_fr",
        ),
        migrations.AddField(
            model_name="servicedetail",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="servicedetail",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
