# Generated by Django 4.2.3 on 2023-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_position_experience_contract_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='client',
            field=models.CharField(default='dfjkjfd', max_length=200),
            preserve_default=False,
        ),
    ]
