# Generated by Django 5.1.4 on 2024-12-07 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0003_remove_service_details_en_remove_service_details_fr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicedetail",
            name="order",
        ),
    ]
