# Generated by Django 5.1.4 on 2024-12-07 23:10

import datetime
import django.db.models.deletion
import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_remove_servicedetail_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("resume", models.TextField()),
                ("resume_en", models.TextField(null=True)),
                ("resume_fr", models.TextField(null=True)),
                ("body", models.TextField()),
                ("body_en", models.TextField(null=True)),
                ("body_fr", models.TextField(null=True)),
                ("creation_date", models.DateField(default=datetime.datetime.now)),
                (
                    "image",
                    models.ImageField(
                        null=True,
                        storage=django_minio_backend.models.MinioBackend(
                            bucket_name="portfolio-media"
                        ),
                        upload_to="blog/",
                    ),
                ),
                ("url", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="LifeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("entity", models.CharField(max_length=200, null=True)),
                ("entity_en", models.CharField(max_length=200, null=True)),
                ("entity_fr", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("description_fr", models.TextField(null=True)),
                ("date", models.DateField(null=True)),
                ("kind", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, null=True)),
                ("title_en", models.CharField(max_length=200, null=True)),
                ("title_fr", models.CharField(max_length=200, null=True)),
                ("short_description", models.CharField(max_length=200, null=True)),
                ("short_description_en", models.CharField(max_length=200, null=True)),
                ("short_description_fr", models.CharField(max_length=200, null=True)),
                ("description", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("description_fr", models.TextField(null=True)),
                ("order", models.IntegerField(default=0)),
                ("url", models.CharField(blank=True, max_length=300, null=True)),
                ("github", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.RemoveField(
            model_name="language",
            name="skill",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="skill",
        ),
        migrations.DeleteModel(
            name="ServiceDetail",
        ),
        migrations.RemoveField(
            model_name="softskill",
            name="skill",
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="skill",
            name="title_fr",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="details",
            field=models.ManyToManyField(to="portfolio.skill"),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.ManyToManyField(to="portfolio.blogcategory"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="portfolio.blogpost",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.ManyToManyField(to="portfolio.skill"),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="Projet",
        ),
        migrations.DeleteModel(
            name="SoftSkill",
        ),
        migrations.DeleteModel(
            name="Blog",
        ),
    ]
