# Generated by Django 4.2.3 on 2023-10-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertise',
            name='skill',
        ),
        migrations.AddField(
            model_name='expertise',
            name='skill',
            field=models.ManyToManyField(related_name='expertises', to='portfolio.skill'),
        ),
    ]
