# Generated by Django 5.1.4 on 2024-12-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_blogpost_lifeevent_project_remove_blog_category_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="BlogPostComment",
        ),
    ]
