# Generated by Django 5.1.4 on 2024-12-07 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_comment_blogpostcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="order",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(limit_value=1)]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="order",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(limit_value=1)]
            ),
        ),
    ]
