# Generated by Django 4.2.3 on 2023-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_name_skill_title_remove_education_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expertise',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='language',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='softskill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
