# Generated by Django 4.2.3 on 2023-10-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_education_order_experience_order_expertise_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='lang',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='softskill',
            old_name='skill',
            new_name='title',
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
