# Generated by Django 4.2.3 on 2023-10-19 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_rename_lang_language_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='order',
        ),
    ]
