# Generated by Django 4.2.6 on 2023-10-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
