# Generated by Django 4.2.6 on 2023-10-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_service_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertise',
            name='image',
            field=models.ImageField(null=True, upload_to='expertises/'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
