# Generated by Django 4.2.6 on 2023-10-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_expertise_image_expertise_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(default='Hello', max_length=200),
            preserve_default=False,
        ),
    ]
