# Generated by Django 4.2.6 on 2023-10-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_education_end_date_alter_education_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertise',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('short_description', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=100, null=True)),
                ('details', models.ManyToManyField(to='portfolio.skill')),
            ],
        ),
    ]
