# Generated by Django 4.2.6 on 2023-10-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_expertise_url_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
