# Generated by Django 4.2.6 on 2023-10-26 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_projet_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='image',
            field=models.FileField(null=True, upload_to='projets/'),
        ),
    ]
