# Generated by Django 4.2.6 on 2023-10-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_projet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='github',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='url',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
