# Generated by Django 4.2.6 on 2023-10-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_projet_github_alter_projet_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='image',
        ),
    ]
