# Generated by Django 4.2.6 on 2023-10-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_projet_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
