# Generated by Django 4.2.6 on 2023-10-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_projet_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='details',
            new_name='skill',
        ),
    ]
