# Generated by Django 4.2.6 on 2023-10-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_rename_details_projet_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('resume', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('image', models.FileField(upload_to='blog/')),
                ('url', models.CharField(max_length=200)),
                ('category', models.ManyToManyField(to='portfolio.blogcategory')),
            ],
        ),
    ]
