# Generated by Django 4.2.6 on 2023-11-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_blogcategory_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategory',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
