# Generated by Django 4.2.6 on 2023-11-23 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='creation_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
