# Generated by Django 4.2.6 on 2023-11-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0029_rename_text_comment_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
