# Generated by Django 4.2.7 on 2024-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0031_comment_parent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="language",
            old_name="title",
            new_name="skill",
        ),
        migrations.RenameField(
            model_name="softskill",
            old_name="title",
            new_name="skill",
        ),
        migrations.AlterField(
            model_name="service",
            name="url",
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
